import type { ProcessStage } from "@/types/content";

export const processStages: ProcessStage[] = [
  { number: "01", title: "Discovery & Audit", shortTitle: "Audit", description: "We inspect product risk, release flow, test assets, environments, and failure history.", inputs: "Architecture, release cadence, current suites, known pain points", deliverable: "System map and prioritized findings", outcome: "A shared view of the reliability constraints" },
  { number: "02", title: "Testing Strategy", shortTitle: "Strategy", description: "We decide what deserves coverage, at which layer, and how often it should run.", inputs: "Risk map, customer journeys, service boundaries", deliverable: "Coverage model and execution tiers", outcome: "A strategy linked to release decisions" },
  { number: "03", title: "Architecture", shortTitle: "Architecture", description: "We define frameworks, fixtures, test data, environments, and reporting boundaries.", inputs: "Stack constraints, CI capacity, team ownership", deliverable: "Technical design and implementation plan", outcome: "A maintainable foundation before suite growth" },
  { number: "04", title: "Implementation", shortTitle: "Implementation", description: "We build representative vertical slices before scaling repeatable patterns.", inputs: "Access, stable environments, prioritized scenarios", deliverable: "Working suites, fixtures, and documentation", outcome: "Useful coverage that the team can extend" },
  { number: "05", title: "CI/CD Integration", shortTitle: "CI/CD Integration", description: "We connect test layers to the right delivery events with useful diagnostics.", inputs: "Pipeline definitions, branch policy, runtime targets", deliverable: "Quality gates, reports, and failure routing", outcome: "Fast evidence inside the engineering workflow" },
  { number: "06", title: "Monitoring & Improvement", shortTitle: "Continuous Improvement", description: "We track signal quality, runtime, flakiness, and escaped risk as the product changes.", inputs: "Execution data, incidents, release outcomes", deliverable: "Health review and improvement backlog", outcome: "A system that stays reliable instead of decaying" },
];
